name: Deploy Nginx to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.AWS_EC2_HOST }}
        username: ${{ secrets.AWS_EC2_USER }}
        key: ${{ secrets.AWS_SSH_KEY }}
        port: 22
        script: |
          # Instalar Docker si no está instalado
          if ! command -v docker &> /dev/null
          then
            sudo yum update -y
            sudo amazon-linux-extras install docker -y
            sudo service docker start
            sudo usermod -a -G docker $USER
          fi

          # Crear directorio de despliegue
          mkdir -p ~/deploy

          # Subir archivos
          scp -o StrictHostKeyChecking=no Dockerfile index.html ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }}:~/deploy

          # Construir y ejecutar la imagen de Docker
          ssh ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} << 'EOF'
            cd ~/deploy
            docker build -t simple-nginx .
            docker stop simple-nginx || true
            docker rm simple-nginx || true
            docker run -d --name simple-nginx -p 80:80 simple-nginx
          EOF

